### ISSUE TITLE
How change inputType?

### ISSUE THREAD

**Issue by NataliyaMokretsova** [poovamraj/PinEditTextField#3] opened 2018-08-08 14:57 UTC
Hi, how I can change "inputType" to "numberDigital", in xml it does'n work.

**Comment by poovamraj** [comment] 2018-08-08 15:14
Hello,

I guess the problem can be because you are referring to the "inputType" as "numberDigital"

If what you are looking for is number keypad then these are all the following supported values by Android

- number
- numberSigned
- numberDecimal
- numberPassword

I just checked with the "inputType" value as "number" in xml and it worked. You can find the screenshot below

Hope this answers your question. Do let me know If I have not helped you with this. I would be happy to solve the problem.

<img src="https://user-images.githubusercontent.com/15910425/43846185-546a8766-9b4b-11e8-8477-2671bfffe2ed.jpg" width="240">

**Comment by poovamraj** [comment] 2018-08-09 06:02
Hello,

Hope the answer above solved your problem, feel to reopen this ticket if you face any problems. I would be happy to help

**Comment by NataliyaMokretsova** [comment] 2018-08-09 06:42
Hello, 

I incorrectly wrote, I used the "inputType" value as "numberDecimal", but it doesn't work. Now I set the "inputType" value as "number" and it doesn't work too. 

My xml:

<com.poovam.pinedittextfield.CirclePinField
android:id="@+id/pinView"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:layout_below="@+id/secondLabel"
android:layout_centerHorizontal="true"
android:layout_marginTop="140dp"
android:background="@null"
android:inputType="number"
app:circleRadius="12dp"
app:fillerColor="@color/gray"
app:distanceInBetween="10dp"
app:highlightColor="@color/white"
app:fieldColor="@color/white"/>

![screenshot_20180809-093908_24](https://user-images.githubusercontent.com/20399862/43882486-75269ff4-9bb8-11e8-9895-eb33005e7027.jpg)

**Comment by poovamraj** [comment] 2018-08-09 06:50
Got the issue will provide a fixed build in next 5 minutes

**Comment by NataliyaMokretsova** [comment] 2018-08-09 06:56
Thank you for so quick help

**Comment by poovamraj** [comment] 2018-08-09 06:59
The problem is resolved in the latest version.
`implementation 'com.poovam:pin-edittext-field:1.0.4'`

Thank you for reporting this issue :) Happy to help.

**Comment by poovamraj** [comment] 2018-08-09 06:59
``

**Closed as completed by poovamraj** 2018-08-09 06:59 UTC
